// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVeFyOc_PZoQi1qPab1Eei0xQ9USeYuNc',
    appId: '1:381174357527:web:your_web_app_id',
    messagingSenderId: '381174357527',
    projectId: 'cryptosquare-1c4e5',
    authDomain: 'cryptosquare-1c4e5.firebaseapp.com',
    storageBucket: 'cryptosquare-1c4e5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVeFyOc_PZoQi1qPab1Eei0xQ9USeYuNc',
    appId: '1:381174357527:android:your_android_app_id',
    messagingSenderId: '381174357527',
    projectId: 'cryptosquare-1c4e5',
    storageBucket: 'cryptosquare-1c4e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVeFyOc_PZoQi1qPab1Eei0xQ9USeYuNc',
    appId: '1:381174357527:ios:52fd3d435110d2ab9c8652',
    messagingSenderId: '381174357527',
    projectId: 'cryptosquare-1c4e5',
    storageBucket: 'cryptosquare-1c4e5.firebasestorage.app',
    iosBundleId: 'org.cryptosquare.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVeFyOc_PZoQi1qPab1Eei0xQ9USeYuNc',
    appId: '1:381174357527:ios:52fd3d435110d2ab9c8652',
    messagingSenderId: '381174357527',
    projectId: 'cryptosquare-1c4e5',
    storageBucket: 'cryptosquare-1c4e5.firebasestorage.app',
    iosBundleId: 'org.cryptosquare.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVeFyOc_PZoQi1qPab1Eei0xQ9USeYuNc',
    appId: '1:381174357527:web:your_web_app_id',
    messagingSenderId: '381174357527',
    projectId: 'cryptosquare-1c4e5',
    authDomain: 'cryptosquare-1c4e5.firebaseapp.com',
    storageBucket: 'cryptosquare-1c4e5.firebasestorage.app',
  );
}
